version: "3.9"

services:
  nextjs-app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    environment:
      - NODE_ENV=production
    restart: unless-stopped